# MUSUBI Project Configuration
name: COBOL2Java
description: A software project using MUSUBI SDD
locale: ja
version: "0.1.0"
created: 2025-12-11

# Technology Stack
tech_stack:
  approach: undecided
  languages:
    - undecided  # To be determined
