# MUSUBI Project Configuration
name: COBOL2Java
description: COBOL to Java automated conversion tool with LLM integration
locale: ja
version: "1.2.0"
created: 2025-12-11
updated: 2025-12-12

# Technology Stack
tech_stack:
  approach: hybrid-rule-llm
  languages:
    - TypeScript 5.x
    - Java 11/17/21
  runtime: Node.js 20 LTS
  package_manager: pnpm
  test_framework: Vitest
  llm_providers:
    - GitHub Copilot
    - OpenAI
    - Anthropic Claude
    - Ollama

# Current Status
status:
  tests: 128
  transformation_patterns: 130+
  intrinsic_functions: 60+
  coverage:
    procedure_division: 85%
    data_division: 50%
    environment_division: 15%
    identification_division: 14%
    overall: 70%
